### ISSUE TITLE
Code doesn't work with current version of warp

### ISSUE THREAD

**Issue by rwboyer** [zupzup/warp-upload-download-example#1]
I'll open an issue with the warp repository but I found your example helpful while evaluating the warp package as an alternative to some of my Golang gin-gonic servers down the road.

The issue lies in the absolutely undocumented features of warp - specifically body stream/multipart form part stream

The way this seems to have worked earlier is that warp::Buf worked like byte::Buf that is no longer the case and now breaks the compile. In this section of code data no longer converts to byte::Buf

```rust
            let value = p
                .stream()
                .try_fold(Vec::new(), |mut vec, data| {
                    vec.put(data);
                    async move { Ok(vec) }
                })
                .await
                .map_err(|e| {
                    eprintln!("reading file error: {}", e);
                    warp::reject::reject()
                })?;

```

See here:

```
   Compiling warp-upload-download-example v0.1.0 (/Volumes/LaCie2/dev/rust-test/upload-example/warp-upload-download-example)
error[E0277]: the trait bound `impl warp::Buf: bytes::Buf` is not satisfied
  --> src/main.rs:56:29
   |
56 |                     vec.put(data);
   |                             ^^^^ the trait `bytes::Buf` is not implemented for `impl warp::Buf`

```

I've not looked too deeply into this myself yet but just off-handedly I hav no idea why the warp maintainers would cause this to not work on purpose, I'd imagine that for 99.999% of the cases where one would want a "stream" they'd want a byte stream.

Just thought you'd like to know since you have about the only relevant and well done example of a critical reason why one would even be looking at warp that no longer works under 0.3. Also if you have any insight as to the fix of the top of your head it would be helpful.

**Comment by rwboyer** [comment]
Sorry, 

Just found the issue. 

pinning to bytes crate prior to version 1.0 is the cause of the problem. warp change to bytes v1.0 as of warp v3.0

**Comment by zupzup** [comment]
Hey @rwboyer 

Thanks for making me aware of this - I updated the deps (warp 0.3, Tokio 1.12, bytes 1.0) and pushed it.
